# Generated by Django 5.2.4 on 2025-11-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='correo_encargado',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='nombre_encargado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre_departamento',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
