# Generated by Django 5.2.4 on 2025-11-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_departamento_correo_encargado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='correo_encargado',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='nombre_encargado',
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre_departamento',
            field=models.CharField(max_length=200),
        ),
    ]
