# Generated by Django 5.2.4 on 2025-11-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_remove_departamento_correo_encargado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='correo_encargado',
            field=models.EmailField(default='sin_email@municipalidad.cl', max_length=254),
        ),
        migrations.AddField(
            model_name='departamento',
            name='nombre_encargado',
            field=models.CharField(default='Sin Encargado', max_length=100),
        ),
    ]
