# Generated by Django 5.2.4 on 2025-11-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='id_direccion',
        ),
        migrations.AddField(
            model_name='direccion',
            name='correo_encargado',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='direccion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='nombre_encargado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='nombre_direccion',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
