# Generated by Django 5.2.4 on 2025-11-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0002_alter_direccion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='correo_encargado',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='nombre_encargado',
        ),
        migrations.AddField(
            model_name='direccion',
            name='id_direccion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='nombre_direccion',
            field=models.CharField(max_length=100),
        ),
    ]
