# Generated by Django 5.2.4 on 2025-11-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0004_direccion_correo_encargado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='correo_encargado',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='nombre_encargado',
        ),
    ]
