# Generated by Django 5.2.4 on 2025-10-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoincidencia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
