# Generated by Django 5.2.4 on 2025-11-24 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
        ('encuesta', '0001_initial'),
        ('incidencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='incidencia.solicitudincidencia'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='id_tipo_incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencia.tipoincidencia'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='id_encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_set', to='encuesta.encuesta'),
        ),
    ]
