# Generated by Django 5.2.4 on 2025-11-03 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
        ('incidencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='id_tipo_incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencia.tipoincidencia'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='obligatoria',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('SI_NO', 'Sí/No')], default='TEXTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='descripcion_incidente',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='id_encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='encuesta.encuesta'),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='TipoIncidencia',
        ),
    ]
