# Generated by Django 5.2.4 on 2025-11-03 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_alter_encuesta_id_tipo_incidencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_incidencia', models.CharField(max_length=240)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de incidencia',
                'verbose_name_plural': 'Tipo de incidencias',
                'db_table': 'tipo_incidencia',
            },
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='obligatoria',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='tipo_pregunta',
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='descripcion_incidente',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='id_encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=1000)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de pregunta',
                'verbose_name_plural': 'Respuestas de preguntas',
                'db_table': 'respuesta_pregunta',
            },
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='id_tipo_incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.tipoincidencia'),
        ),
    ]
