# Generated by Django 5.2.4 on 2025-10-07 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_tipoincidencia_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
