# Generated by Django 5.2.4 on 2025-11-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='encuestas/audios/', verbose_name='Audio (Opcional)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='encuestas/imagenes/', verbose_name='Imagen (Opcional)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='encuestas/videos/', verbose_name='Video (Opcional)'),
        ),
    ]
