# Generated by Django 5.2.4 on 2025-11-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_archivosolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosolicitud',
            name='tipo',
            field=models.CharField(choices=[('evidencia', 'Evidencia Original'), ('resolucion', 'Archivo de Resolución')], default='evidencia'),
        ),
    ]
