# Generated by Django 5.2.4 on 2025-11-18 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_encuesta_audio_encuesta_imagen_encuesta_video'),
        ('incidencia', '0005_remove_solicitudincidencia_audio_incidencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='video',
        ),
        migrations.CreateModel(
            name='ArchivoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='solicitudes/adjuntos/%Y/%m/%d/', verbose_name='Archivo adjunto')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo_contenido', models.CharField(max_length=100)),
                ('tamaño', models.BigIntegerField(help_text='Tamaño en bytes')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='incidencia.solicitudincidencia')),
            ],
            options={
                'verbose_name': 'Archivo adjunto',
                'verbose_name_plural': 'Archivos adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
