# Generated by Django 5.2.4 on 2025-10-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_encuesta_creado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='ubicacion',
        ),
    ]
