# Generated by Django 5.2.4 on 2025-11-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_archivosolicitud_tipo'),
        ('encuesta', '0004_remove_encuesta_audio_remove_encuesta_imagen_and_more'),
    ]

    operations = [
    ]
