# Generated by Django 5.2.4 on 2025-11-01 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=48)),
                ('apellido', models.CharField(max_length=48)),
                ('username', models.CharField(max_length=24, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=128)),
                ('session_token', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('first_session', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='direccion.direccion')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.profile')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['created'],
            },
        ),
    ]
