# Generated by Django 5.2.4 on 2025-10-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(
                blank=True, default="Activo", max_length=100, null=True
            ),
        ),
    ]
