# Generated by Django 5.2.4 on 2025-11-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudincidencia',
            name='ubicacion',
            field=models.CharField(default='ubiacion'),
            preserve_default=False,
        ),
    ]
