# Generated by Django 5.2.4 on 2025-11-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0003_solicitudincidencia_descripcion_rechazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudincidencia',
            name='descripcion_reabrir',
            field=models.TextField(blank=True, null=True),
        ),
    ]
