# Generated by Django 5.2.4 on 2025-11-02 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_incidencia', models.CharField(max_length=240, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='departamento.departamento')),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='direccion.direccion')),
            ],
            options={
                'verbose_name': 'Tipo de Incidencia',
                'verbose_name_plural': 'Tipos de Incidencia',
                'db_table': 'tipo_incidencia_incidencia',
            },
        ),
    ]
