# Generated by Django 5.2.4 on 2025-11-24 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
        ('direccion', '0001_initial'),
        ('encuesta', '0001_initial'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('derivada', 'Derivada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada')], default='abierta', max_length=20)),
                ('descripcion_resolucion', models.TextField(blank=True, null=True)),
                ('descripcion_rechazo', models.TextField(blank=True, null=True)),
                ('descripcion_reabrir', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to='register.user')),
                ('cuadrilla_asignada', models.ForeignKey(blank=True, limit_choices_to={'perfil__id': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to='register.user')),
                ('departamento_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_asignadas', to='departamento.departamento')),
                ('direccion_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_asignadas', to='direccion.direccion')),
                ('encuesta_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='encuesta.encuesta')),
            ],
            options={
                'verbose_name': 'Solicitud de Incidencia',
                'verbose_name_plural': 'Solicitudes de Incidencia',
                'db_table': 'solicitud_incidencia',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_incidencia', models.CharField(max_length=240, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='departamento.departamento')),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='direccion.direccion')),
            ],
            options={
                'verbose_name': 'Tipo de Incidencia',
                'verbose_name_plural': 'Tipos de Incidencia',
                'db_table': 'tipo_incidencia',
            },
        ),
        migrations.CreateModel(
            name='RespuestaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_solicitud', to='encuesta.pregunta')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='incidencia.solicitudincidencia')),
            ],
            options={
                'verbose_name': 'Respuesta de Solicitud',
                'verbose_name_plural': 'Respuestas de Solicitud',
                'db_table': 'respuesta_solicitud',
                'unique_together': {('solicitud', 'pregunta')},
            },
        ),
    ]
