# Generated by Django 5.2.4 on 2025-11-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudincidencia',
            name='imagen_resolucion',
            field=models.ImageField(blank=True, null=True, upload_to='resoluciones/'),
        ),
    ]
