# Generated by Django 5.2.4 on 2025-11-08 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
        ('direccion', '0001_initial'),
        ('encuesta', '0002_initial'),
        ('incidencia', '0002_solicitudincidencia_ubicacion'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudincidencia',
            options={'ordering': ['-creado']},
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='cuadrilla_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_cuadrilla', to='register.user'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='departamento_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departamento.departamento'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='direccion_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='direccion.direccion'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='encuesta_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
