# Generated by Django 5.2.4 on 2025-11-18 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
        ('direccion', '0001_initial'),
        ('encuesta', '0003_archivosolicitud'),
        ('incidencia', '0002_solicitudincidencia_ubicacion'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudincidencia',
            name='descripcion_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuestasolicitud',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_solicitud', to='encuesta.pregunta'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to='register.user'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='departamento_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_asignadas', to='departamento.departamento'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='direccion_asignada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_asignadas', to='direccion.direccion'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='encuesta_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='encuesta.encuesta'),
        ),
    ]
