# Generated by Django 5.2.4 on 2025-11-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0002_solicitudincidencia_imagen_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudincidencia',
            name='audio_incidencia',
            field=models.FileField(blank=True, null=True, upload_to='incidencias/audios/', verbose_name='Audio de Incidencia'),
        ),
        migrations.AddField(
            model_name='solicitudincidencia',
            name='imagen_incidencia',
            field=models.ImageField(blank=True, null=True, upload_to='incidencias/imagenes/', verbose_name='Imagen de Incidencia'),
        ),
        migrations.AddField(
            model_name='solicitudincidencia',
            name='video_incidencia',
            field=models.FileField(blank=True, null=True, upload_to='incidencias/videos/', verbose_name='Video de Incidencia'),
        ),
    ]
