# Generated by Django 5.2.4 on 2025-11-18 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0002_solicitudincidencia_ubicacion'),
        ('incidencia', '0003_solicitudincidencia_audio_incidencia_and_more'),
    ]

    operations = [
    ]
