# Generated by Django 5.2.4 on 2025-11-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0004_merge_20251118_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='audio_incidencia',
        ),
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='imagen_incidencia',
        ),
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='imagen_resolucion',
        ),
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='video_incidencia',
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('derivada', 'Derivada'), ('rechazada', 'Rechazada'), ('en_revision', 'En Revisión'), ('finalizada', 'Finalizada')], default='abierta', max_length=20),
        ),
    ]
