# Generated by Django 5.2.4 on 2025-11-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0005_remove_solicitudincidencia_audio_incidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudincidencia',
            name='audio_incidencia',
            field=models.FileField(blank=True, null=True, upload_to='incidencias/audio/'),
        ),
        migrations.AddField(
            model_name='solicitudincidencia',
            name='imagen_incidencia',
            field=models.ImageField(blank=True, null=True, upload_to='incidencias/imagen/'),
        ),
        migrations.AddField(
            model_name='solicitudincidencia',
            name='imagen_resolucion',
            field=models.ImageField(blank=True, null=True, upload_to='resoluciones/'),
        ),
        migrations.AddField(
            model_name='solicitudincidencia',
            name='vecino_celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='solicitudincidencia',
            name='vecino_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='solicitudincidencia',
            name='vecino_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudincidencia',
            name='video_incidencia',
            field=models.FileField(blank=True, null=True, upload_to='incidencias/video/'),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
