# Generated by Django 5.2.4 on 2025-11-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0006_solicitudincidencia_audio_incidencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='audio_incidencia',
        ),
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='imagen_incidencia',
        ),
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='imagen_resolucion',
        ),
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='vecino_celular',
        ),
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='vecino_email',
        ),
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='vecino_nombre',
        ),
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='video_incidencia',
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('derivada', 'Derivada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada')], default='abierta', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='ubicacion',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
