# Generated by Django 5.2.4 on 2025-11-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0007_remove_solicitudincidencia_audio_incidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudincidencia',
            name='celular_vecino',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='solicitudincidencia',
            name='email_vecino',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='solicitudincidencia',
            name='nombre_vecino',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='ubicacion',
            field=models.CharField(max_length=255),
        ),
    ]
