# Generated by Django 5.2.4 on 2025-11-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0004_solicitudincidencia_descripcion_reabrir'),
        ('incidencia', '0008_solicitudincidencia_celular_vecino_and_more'),
    ]

    operations = [
    ]
