# Generated by Django 5.2.4 on 2025-11-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0009_merge_20251122_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='celular_vecino',
        ),
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='email_vecino',
        ),
        migrations.RemoveField(
            model_name='solicitudincidencia',
            name='nombre_vecino',
        ),
        migrations.AlterField(
            model_name='solicitudincidencia',
            name='ubicacion',
            field=models.CharField(),
        ),
    ]
