# Generated by Django 5.2.4 on 2025-11-21 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0005_remove_departamento_correo_encargado_and_more'),
        ('direccion', '0005_remove_direccion_correo_encargado_and_more'),
        ('incidencia', '0010_remove_solicitudincidencia_celular_vecino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoincidencia',
            name='id_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='departamento.departamento'),
        ),
        migrations.AlterField(
            model_name='tipoincidencia',
            name='id_direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='direccion.direccion'),
        ),
    ]
